// #############################################################################
// This file is part of the "garf" package of the "Eureka" project.
// It is distributed under the MIT License. Refer to the LICENSE file for more
// information.
//
// Website: http://www.github.com/sivachandra/eureka
// #############################################################################

// Package garf provides API to read DWARF debug info from ELF files.
package garf

type DwTag uint16
type DwAt uint16
type DwForm uint16
type DwLang uint16
type DwUnitType uint8
type DwAte uint8
type DwLnOpcode uint8
type DwLnFormat uint16

const (
	NullAbbrevEntry = uint64(0)
	NullAttrEntry   = uint64(0)
	NullFormEntry   = uint64(0)
)

const (
	DW_UT_compile = DwUnitType(0x01)
	DW_UT_type    = DwUnitType(0x02)
	DW_UT_partial = DwUnitType(0x03)
)

const (
	DW_TAG_array_type               = DwTag(0x01)
	DW_TAG_class_type               = DwTag(0x02)
	DW_TAG_entry_point              = DwTag(0x03)
	DW_TAG_enumeration_type         = DwTag(0x04)
	DW_TAG_formal_parameter         = DwTag(0x05)
	DW_TAG_imported_declaration     = DwTag(0x08)
	DW_TAG_label                    = DwTag(0x0a)
	DW_TAG_lexical_block            = DwTag(0x0b)
	DW_TAG_member                   = DwTag(0x0d)
	DW_TAG_pointer_type             = DwTag(0x0f)
	DW_TAG_reference_type           = DwTag(0x10)
	DW_TAG_compile_unit             = DwTag(0x11)
	DW_TAG_string_type              = DwTag(0x12)
	DW_TAG_structure_type           = DwTag(0x13)
	DW_TAG_subroutine_type          = DwTag(0x15)
	DW_TAG_typedef                  = DwTag(0x16)
	DW_TAG_union_type               = DwTag(0x17)
	DW_TAG_unspecified_parameters   = DwTag(0x18)
	DW_TAG_variant                  = DwTag(0x19)
	DW_TAG_common_block             = DwTag(0x1a)
	DW_TAG_common_inclusion         = DwTag(0x1b)
	DW_TAG_inheritance              = DwTag(0x1c)
	DW_TAG_inlined_subroutine       = DwTag(0x1d)
	DW_TAG_module                   = DwTag(0x1e)
	DW_TAG_ptr_to_member_type       = DwTag(0x1f)
	DW_TAG_set_type                 = DwTag(0x20)
	DW_TAG_subrange_type            = DwTag(0x21)
	DW_TAG_with_stmt                = DwTag(0x22)
	DW_TAG_access_declaration       = DwTag(0x23)
	DW_TAG_base_type                = DwTag(0x24)
	DW_TAG_catch_block              = DwTag(0x25)
	DW_TAG_const_type               = DwTag(0x26)
	DW_TAG_constant                 = DwTag(0x27)
	DW_TAG_enumerator               = DwTag(0x28)
	DW_TAG_file_type                = DwTag(0x29)
	DW_TAG_friend                   = DwTag(0x2a)
	DW_TAG_namelist                 = DwTag(0x2b)
	DW_TAG_namelist_item            = DwTag(0x2c)
	DW_TAG_packed_type              = DwTag(0x2d)
	DW_TAG_subprogram               = DwTag(0x2e)
	DW_TAG_template_type_parameter  = DwTag(0x2f)
	DW_TAG_template_value_parameter = DwTag(0x30)
	DW_TAG_thrown_type              = DwTag(0x31)
	DW_TAG_try_block                = DwTag(0x32)
	DW_TAG_variant_part             = DwTag(0x33)
	DW_TAG_variable                 = DwTag(0x34)
	DW_TAG_volatile_type            = DwTag(0x35)
	DW_TAG_dwarf_procedure          = DwTag(0x36)
	DW_TAG_restrict_type            = DwTag(0x37)
	DW_TAG_interface_type           = DwTag(0x38)
	DW_TAG_namespace                = DwTag(0x39)
	DW_TAG_imported_module          = DwTag(0x3a)
	DW_TAG_unspecified_type         = DwTag(0x3b)
	DW_TAG_partial_unit             = DwTag(0x3c)
	DW_TAG_imported_unit            = DwTag(0x3d)
	DW_TAG_condition                = DwTag(0x3f)
	DW_TAG_shared_type              = DwTag(0x40)
	DW_TAG_type_unit                = DwTag(0x41)
	DW_TAG_rvalue_reference_type    = DwTag(0x42)
	DW_TAG_template_alias           = DwTag(0x43)
	DW_TAG_coarray_type             = DwTag(0x44)
	DW_TAG_generic_subrange         = DwTag(0x45)
	DW_TAG_dynamic_type             = DwTag(0x46)
	DW_TAG_atomic_type              = DwTag(0x47)
	DW_TAG_call_site                = DwTag(0x48)
	DW_TAG_call_site_parameter      = DwTag(0x49)

	// User-defined tags.
	DW_TAG_lo_user = DwTag(0x4080)

	DW_TAG_MIPS_loop                   = DwTag(0x4081)
	DW_TAG_format_label                = DwTag(0x4101)
	DW_TAG_function_template           = DwTag(0x4102)
	DW_TAG_class_template              = DwTag(0x4103)
	DW_TAG_GNU_template_template_param = DwTag(0x4106)
	DW_TAG_GNU_template_parameter_pack = DwTag(0x4107)
	DW_TAG_GNU_formal_parameter_pack   = DwTag(0x4108)
	DW_TAG_APPLE_property              = DwTag(0x4200)

	DW_TAG_hi_user = DwTag(0xffff)
)

const (
	DW_CHILDREN_no  = byte(0x00)
	DW_CHILDREN_yes = byte(0x01)
)

const (
	DW_AT_sibling                 = DwAt(0x01)
	DW_AT_location                = DwAt(0x02)
	DW_AT_name                    = DwAt(0x03)
	DW_AT_ordering                = DwAt(0x09)
	DW_AT_byte_size               = DwAt(0x0b)
	DW_AT_bit_offset              = DwAt(0x0c)
	DW_AT_bit_size                = DwAt(0x0d)
	DW_AT_stmt_list               = DwAt(0x10)
	DW_AT_low_pc                  = DwAt(0x11)
	DW_AT_high_pc                 = DwAt(0x12)
	DW_AT_language                = DwAt(0x13)
	DW_AT_discr                   = DwAt(0x15)
	DW_AT_discr_value             = DwAt(0x16)
	DW_AT_visibility              = DwAt(0x17)
	DW_AT_import                  = DwAt(0x18)
	DW_AT_string_length           = DwAt(0x19)
	DW_AT_common_reference        = DwAt(0x1a)
	DW_AT_comp_dir                = DwAt(0x1b)
	DW_AT_const_value             = DwAt(0x1c)
	DW_AT_containing_type         = DwAt(0x1d)
	DW_AT_default_value           = DwAt(0x1e)
	DW_AT_inline                  = DwAt(0x20)
	DW_AT_is_optional             = DwAt(0x21)
	DW_AT_lower_bound             = DwAt(0x22)
	DW_AT_producer                = DwAt(0x25)
	DW_AT_prototyped              = DwAt(0x27)
	DW_AT_return_addr             = DwAt(0x2a)
	DW_AT_start_scope             = DwAt(0x2c)
	DW_AT_bit_stride              = DwAt(0x2e)
	DW_AT_upper_bound             = DwAt(0x2f)
	DW_AT_abstract_origin         = DwAt(0x31)
	DW_AT_accessibility           = DwAt(0x32)
	DW_AT_address_class           = DwAt(0x33)
	DW_AT_artificial              = DwAt(0x34)
	DW_AT_base_types              = DwAt(0x35)
	DW_AT_calling_convention      = DwAt(0x36)
	DW_AT_count                   = DwAt(0x37)
	DW_AT_data_member_location    = DwAt(0x38)
	DW_AT_decl_column             = DwAt(0x39)
	DW_AT_decl_file               = DwAt(0x3a)
	DW_AT_decl_line               = DwAt(0x3b)
	DW_AT_declaration             = DwAt(0x3c)
	DW_AT_discr_list              = DwAt(0x3d)
	DW_AT_encoding                = DwAt(0x3e)
	DW_AT_external                = DwAt(0x3f)
	DW_AT_frame_base              = DwAt(0x40)
	DW_AT_friend                  = DwAt(0x41)
	DW_AT_identifier_case         = DwAt(0x42)
	DW_AT_macro_info              = DwAt(0x43)
	DW_AT_namelist_item           = DwAt(0x44)
	DW_AT_priority                = DwAt(0x45)
	DW_AT_segment                 = DwAt(0x46)
	DW_AT_specification           = DwAt(0x47)
	DW_AT_static_link             = DwAt(0x48)
	DW_AT_type                    = DwAt(0x49)
	DW_AT_use_location            = DwAt(0x4a)
	DW_AT_variable_parameter      = DwAt(0x4b)
	DW_AT_virtuality              = DwAt(0x4c)
	DW_AT_vtable_elem_location    = DwAt(0x4d)
	DW_AT_allocated               = DwAt(0x4e)
	DW_AT_associated              = DwAt(0x4f)
	DW_AT_data_location           = DwAt(0x50)
	DW_AT_byte_stride             = DwAt(0x51)
	DW_AT_entry_pc                = DwAt(0x52)
	DW_AT_use_UTF8                = DwAt(0x53)
	DW_AT_extension               = DwAt(0x54)
	DW_AT_ranges                  = DwAt(0x55)
	DW_AT_trampoline              = DwAt(0x56)
	DW_AT_call_column             = DwAt(0x57)
	DW_AT_call_file               = DwAt(0x58)
	DW_AT_call_line               = DwAt(0x59)
	DW_AT_description             = DwAt(0x5a)
	DW_AT_binary_scale            = DwAt(0x5b)
	DW_AT_decimal_scale           = DwAt(0x5c)
	DW_AT_small                   = DwAt(0x5d)
	DW_AT_decimal_sign            = DwAt(0x5e)
	DW_AT_digit_count             = DwAt(0x5f)
	DW_AT_picture_string          = DwAt(0x60)
	DW_AT_mutable                 = DwAt(0x61)
	DW_AT_threads_scaled          = DwAt(0x62)
	DW_AT_explicit                = DwAt(0x63)
	DW_AT_object_pointer          = DwAt(0x64)
	DW_AT_endianity               = DwAt(0x65)
	DW_AT_elemental               = DwAt(0x66)
	DW_AT_pure                    = DwAt(0x67)
	DW_AT_recursive               = DwAt(0x68)
	DW_AT_signature               = DwAt(0x69)
	DW_AT_main_subprogram         = DwAt(0x6a)
	DW_AT_data_bit_offset         = DwAt(0x6b)
	DW_AT_const_expr              = DwAt(0x6c)
	DW_AT_enum_class              = DwAt(0x6d)
	DW_AT_linkage_name            = DwAt(0x6e)
	DW_AT_string_length_bit_size  = DwAt(0x6f)
	DW_AT_string_length_byte_size = DwAt(0x70)
	DW_AT_rank                    = DwAt(0x71)
	DW_AT_str_offsets_base        = DwAt(0x72)
	DW_AT_addr_base               = DwAt(0x73)
	DW_AT_ranges_base             = DwAt(0x74)
	DW_AT_dwo_id                  = DwAt(0x75)
	DW_AT_dwo_name                = DwAt(0x76)
	DW_AT_reference               = DwAt(0x77)
	DW_AT_rvalue_reference        = DwAt(0x78)
	DW_AT_macros                  = DwAt(0x79)
	DW_AT_call_all_calls          = DwAt(0x7a)
	DW_AT_call_all_source_calls   = DwAt(0x7b)
	DW_AT_call_all_tail_calls     = DwAt(0x7c)
	DW_AT_call_return_pc          = DwAt(0x7d)
	DW_AT_call_value              = DwAt(0x7e)
	DW_AT_call_origin             = DwAt(0x7f)
	DW_AT_call_parameter          = DwAt(0x80)
	DW_AT_call_pc                 = DwAt(0x81)
	DW_AT_call_tail_call          = DwAt(0x82)
	DW_AT_call_target             = DwAt(0x83)
	DW_AT_call_target_clobbered   = DwAt(0x84)
	DW_AT_call_data_location      = DwAt(0x85)
	DW_AT_call_data_value         = DwAt(0x86)
	DW_AT_noreturn                = DwAt(0x87)
	DW_AT_alignment               = DwAt(0x88)
	DW_AT_export_symbols          = DwAt(0x89)
	DW_AT_deleted                 = DwAt(0x8a)
	DW_AT_defaulted               = DwAt(0x8b)

	DW_AT_lo_user = DwAt(0x2000)
	DW_AT_hi_user = DwAt(0x3fff)

	DW_AT_MIPS_loop_begin              = DwAt(0x2002)
	DW_AT_MIPS_tail_loop_begin         = DwAt(0x2003)
	DW_AT_MIPS_epilog_begin            = DwAt(0x2004)
	DW_AT_MIPS_loop_unroll_factor      = DwAt(0x2005)
	DW_AT_MIPS_software_pipeline_depth = DwAt(0x2006)
	DW_AT_MIPS_linkage_name            = DwAt(0x2007)
	DW_AT_MIPS_stride                  = DwAt(0x2008)
	DW_AT_MIPS_abstract_name           = DwAt(0x2009)
	DW_AT_MIPS_clone_origin            = DwAt(0x200a)
	DW_AT_MIPS_has_inlines             = DwAt(0x200b)
	DW_AT_MIPS_stride_byte             = DwAt(0x200c)
	DW_AT_MIPS_stride_elem             = DwAt(0x200d)
	DW_AT_MIPS_ptr_dopetype            = DwAt(0x200e)
	DW_AT_MIPS_allocatable_dopetype    = DwAt(0x200f)
	DW_AT_MIPS_assumed_shape_dopetype  = DwAt(0x2010)

	DW_AT_MIPS_assumed_size = DwAt(0x2011)

	// GNU extensions
	DW_AT_sf_names                       = DwAt(0x2101)
	DW_AT_src_info                       = DwAt(0x2102)
	DW_AT_mac_info                       = DwAt(0x2103)
	DW_AT_src_coords                     = DwAt(0x2104)
	DW_AT_body_begin                     = DwAt(0x2105)
	DW_AT_body_end                       = DwAt(0x2106)
	DW_AT_GNU_vector                     = DwAt(0x2107)
	DW_AT_GNU_template_name              = DwAt(0x2110)
	DW_AT_GNU_call_site_value            = DwAt(0x2111)
	DW_AT_GNU_call_site_data_value       = DwAt(0x2112)
	DW_AT_GNU_call_site_target           = DwAt(0x2113)
	DW_AT_GNU_call_site_target_clobbered = DwAt(0x2114)
	DW_AT_GNU_tail_call                  = DwAt(0x2115)
	DW_AT_GNU_all_tail_call_sites        = DwAt(0x2116)
	DW_AT_GNU_all_call_sites             = DwAt(0x2117)
	DW_AT_GNU_all_source_call_sites      = DwAt(0x2118)
	DW_AT_GNU_macros                     = DwAt(0x2119)
	DW_AT_GNU_odr_signature              = DwAt(0x210f)
	DW_AT_GNU_dwo_name                   = DwAt(0x2130)
	DW_AT_GNU_dwo_id                     = DwAt(0x2131)
	DW_AT_GNU_ranges_base                = DwAt(0x2132)
	DW_AT_GNU_addr_base                  = DwAt(0x2133)
	DW_AT_GNU_pubnames                   = DwAt(0x2134)
	DW_AT_GNU_pubtypes                   = DwAt(0x2135)

	// LLVM project extensions.
	DW_AT_LLVM_include_path  = DwAt(0x3e00)
	DW_AT_LLVM_config_macros = DwAt(0x3e01)
	DW_AT_LLVM_isysroot      = DwAt(0x3e02)

	// Apple extensions.
	DW_AT_APPLE_optimized          = DwAt(0x3fe1)
	DW_AT_APPLE_flags              = DwAt(0x3fe2)
	DW_AT_APPLE_isa                = DwAt(0x3fe3)
	DW_AT_APPLE_block              = DwAt(0x3fe4)
	DW_AT_APPLE_major_runtime_vers = DwAt(0x3fe5)
	DW_AT_APPLE_runtime_class      = DwAt(0x3fe6)
	DW_AT_APPLE_omit_frame_ptr     = DwAt(0x3fe7)
	DW_AT_APPLE_property_name      = DwAt(0x3fe8)
	DW_AT_APPLE_property_getter    = DwAt(0x3fe9)
	DW_AT_APPLE_property_setter    = DwAt(0x3fea)
	DW_AT_APPLE_property_attribute = DwAt(0x3feb)
	DW_AT_APPLE_objc_complete_type = DwAt(0x3fec)
	DW_AT_APPLE_property           = DwAt(0x3fed)
)

const (
	DW_FORM_addr           = DwForm(0x01)
	DW_FORM_block2         = DwForm(0x03)
	DW_FORM_block4         = DwForm(0x04)
	DW_FORM_data2          = DwForm(0x05)
	DW_FORM_data4          = DwForm(0x06)
	DW_FORM_data8          = DwForm(0x07)
	DW_FORM_string         = DwForm(0x08)
	DW_FORM_block          = DwForm(0x09)
	DW_FORM_block1         = DwForm(0x0a)
	DW_FORM_data1          = DwForm(0x0b)
	DW_FORM_flag           = DwForm(0x0c)
	DW_FORM_sdata          = DwForm(0x0d)
	DW_FORM_strp           = DwForm(0x0e)
	DW_FORM_udata          = DwForm(0x0f)
	DW_FORM_ref_addr       = DwForm(0x10)
	DW_FORM_ref1           = DwForm(0x11)
	DW_FORM_ref2           = DwForm(0x12)
	DW_FORM_ref4           = DwForm(0x13)
	DW_FORM_ref8           = DwForm(0x14)
	DW_FORM_ref_udata      = DwForm(0x15)
	DW_FORM_indirect       = DwForm(0x16)
	DW_FORM_sec_offset     = DwForm(0x17)
	DW_FORM_exprloc        = DwForm(0x18)
	DW_FORM_flag_present   = DwForm(0x19)
	DW_FORM_strx           = DwForm(0x1a)
	DW_FORM_addrx          = DwForm(0x1b)
	DW_FORM_ref_sup        = DwForm(0x1c)
	DW_FORM_str_sup        = DwForm(0x1d)
	DW_FORM_data16         = DwForm(0x1e)
	DW_FORM_line_strp      = DwForm(0x1f)
	DW_FORM_ref_sig8       = DwForm(0x20)
	DW_FORM_implicit_const = DwForm(0x21)

	DW_FORM_GNU_addr_index = DwForm(0x1f01)
	DW_FORM_GNU_str_index  = DwForm(0x1f02)
	DW_FORM_GNU_ref_alt    = DwForm(0x1f20)
	DW_FORM_GNU_strp_alt   = DwForm(0x1f21)
)

const (
	DW_LANG_C89            = DwLang(0x0001)
	DW_LANG_C              = DwLang(0x0002)
	DW_LANG_Ada83          = DwLang(0x0003)
	DW_LANG_C_plus_plus    = DwLang(0x0004)
	DW_LANG_Cobol74        = DwLang(0x0005)
	DW_LANG_Cobol85        = DwLang(0x0006)
	DW_LANG_Fortran77      = DwLang(0x0007)
	DW_LANG_Fortran90      = DwLang(0x0008)
	DW_LANG_Pascal83       = DwLang(0x0009)
	DW_LANG_Modula2        = DwLang(0x000a)
	DW_LANG_Java           = DwLang(0x000b)
	DW_LANG_C99            = DwLang(0x000c)
	DW_LANG_Ada95          = DwLang(0x000d)
	DW_LANG_Fortran95      = DwLang(0x000e)
	DW_LANG_PLI            = DwLang(0x000f)
	DW_LANG_ObjC           = DwLang(0x0010)
	DW_LANG_ObjC_plus_plus = DwLang(0x0011)
	DW_LANG_UPC            = DwLang(0x0012)
	DW_LANG_D              = DwLang(0x0013)
	DW_LANG_Python         = DwLang(0x0014)
	DW_LANG_OpenCL         = DwLang(0x0015)
	DW_LANG_Go             = DwLang(0x0016)
	DW_LANG_Modula3        = DwLang(0x0017)
	DW_LANG_Haskell        = DwLang(0x0018)
	DW_LANG_C_plus_plus_03 = DwLang(0x0019)
	DW_LANG_C_plus_plus_11 = DwLang(0x001a)
	DW_LANG_OCaml          = DwLang(0x001b)
	DW_LANG_Rust           = DwLang(0x001c)
	DW_LANG_C11            = DwLang(0x001d)
	DW_LANG_Swift          = DwLang(0x001e)
	DW_LANG_Julia          = DwLang(0x001f)
	DW_LANG_Dylan          = DwLang(0x0020)
	DW_LANG_C_plus_plus_14 = DwLang(0x0021)
	DW_LANG_Fortran03      = DwLang(0x0022)
	DW_LANG_Fortran08      = DwLang(0x0023)
	DW_LANG_lo_user        = DwLang(0x8000)
	DW_LANG_hi_user        = DwLang(0xffff)
)

const (
	DW_ATE_address         = DwAte(0x01)
	DW_ATE_boolean         = DwAte(0x02)
	DW_ATE_complex_float   = DwAte(0x03)
	DW_ATE_float           = DwAte(0x04)
	DW_ATE_signed          = DwAte(0x05)
	DW_ATE_signed_char     = DwAte(0x06)
	DW_ATE_unsigned        = DwAte(0x07)
	DW_ATE_unsigned_char   = DwAte(0x08)
	DW_ATE_imaginary_float = DwAte(0x09)
	DW_ATE_packed_decimal  = DwAte(0x0a)
	DW_ATE_numeric_string  = DwAte(0x0b)
	DW_ATE_edited          = DwAte(0x0c)
	DW_ATE_signed_fixed    = DwAte(0x0d)
	DW_ATE_unsigned_fixed  = DwAte(0x0e)
	DW_ATE_decimal_float   = DwAte(0x0f)
	DW_ATE_UTF             = DwAte(0x10)
	DW_ATE_UCS             = DwAte(0x11)
	DW_ATE_ASCII           = DwAte(0x12)

	DW_ATE_lo_user = DwAte(0x80)
	DW_ATE_hi_user = DwAte(0xff)
)

const (
	DW_LNS_copy               = DwLnOpcode(0x01)
	DW_LNS_advance_pc         = DwLnOpcode(0x02)
	DW_LNS_advance_line       = DwLnOpcode(0x03)
	DW_LNS_set_file           = DwLnOpcode(0x04)
	DW_LNS_set_column         = DwLnOpcode(0x05)
	DW_LNS_negate_stmt        = DwLnOpcode(0x06)
	DW_LNS_set_basic_block    = DwLnOpcode(0x07)
	DW_LNS_const_add_pc       = DwLnOpcode(0x08)
	DW_LNS_fixed_advance_pc   = DwLnOpcode(0x09)
	DW_LNS_set_prologue_end   = DwLnOpcode(0x0a)
	DW_LNS_set_epilogue_begin = DwLnOpcode(0x0b)
	DW_LNS_set_isa            = DwLnOpcode(0x0c)
)

const (
	DW_LNE_end_sequence      = DwLnOpcode(0x01)
	DW_LNE_set_address       = DwLnOpcode(0x02)
	DW_LNE_define_file       = DwLnOpcode(0x03)
	DW_LNE_set_discriminator = DwLnOpcode(0x04)
	DW_LNE_lo_user           = DwLnOpcode(0x80)
	DW_LNE_hi_user           = DwLnOpcode(0xff)
)

const (
	DW_LNCT_path            = DwLnFormat(0x0001)
	DW_LNCT_directory_index = DwLnFormat(0x0002)
	DW_LNCT_timestamp       = DwLnFormat(0x0003)
	DW_LNCT_size            = DwLnFormat(0x0004)
	DW_LNCT_MD5             = DwLnFormat(0x0005)
	DW_LNCT_lo_user         = DwLnFormat(0x2000)
	DW_LNCT_hi_user         = DwLnFormat(0x3fff)
)
